### ISSUE TITLE
fields that we need to have

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/chemical-files-registry#1]
I'd like to have a curated list of file formats that are used in experimental chemistry such that different ELN implementations can refer to the same thing. For example, I'd like to link from the cheminfo registry to some file type definition.  

for files for analytical techniques i'd suggest
```
- technique: 
  - name: 
  - CHMO id: 
 - maintainer: 
 - extension:  
 - version: 
 - description 
 - internetMediaType
 - license
 - examples: []
 - encoding: 
``` 

for molecules/structures the "technique" type would not be there 

for now, we could render it as a static github pages similar to the other registries, but at some point we might as well add a react frontend to explore it 

for the repository i'd suggest a nested folder structure 

```
files
   analyticalTechniques
      xrd 
        bruker-brml 
           definition.yml 
           examples 
```
